-- Agent Work는 Swimming 테이블과 FK·조인 없이 리소스 식별자만 보관한다.
CREATE TABLE agent_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  agent_type varchar(30) NOT NULL,
  status varchar(20) NOT NULL,
  status_source varchar(30) NOT NULL,
  instruction varchar(2000),
  progress_snapshot jsonb,
  result_snapshot jsonb,
  error_snapshot jsonb,
  started_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_agent_sessions_user ON agent_sessions (user_id);

-- 시작 전 Work Item은 세션 없이 등록하며, 여러 Work Item이 같은 세션을 공유한다.
CREATE TABLE agent_work_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  resource_type varchar(30) NOT NULL,
  resource_id varchar(100) NOT NULL,
  agent_session_id bigint,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_agent_work_items_resource UNIQUE (user_id, resource_type, resource_id),
  CONSTRAINT fk_agent_work_items_session FOREIGN KEY (agent_session_id) REFERENCES agent_sessions (id)
);

CREATE INDEX idx_agent_work_items_session ON agent_work_items (agent_session_id);

CREATE TABLE agent_session_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_session_id bigint NOT NULL,
  agent_type varchar(30) NOT NULL,
  event_type varchar(30) NOT NULL,
  payload jsonb NOT NULL,
  source varchar(30) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_agent_session_events_session FOREIGN KEY (agent_session_id) REFERENCES agent_sessions (id)
);

CREATE INDEX idx_agent_session_events_session_created
  ON agent_session_events (agent_session_id, created_at, id);
