CREATE TABLE agent_access_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  name varchar(100) NOT NULL,
  token_prefix varchar(30) NOT NULL,
  token_suffix varchar(6) NOT NULL,
  token_hash varchar(64) NOT NULL,
  scopes varchar(500) NOT NULL,
  expires_at timestamptz,
  last_used_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_agent_access_tokens_hash UNIQUE (token_hash)
);

CREATE INDEX idx_agent_access_tokens_user ON agent_access_tokens (user_id);
CREATE INDEX idx_agent_access_tokens_active ON agent_access_tokens (token_hash, revoked_at, expires_at);
