-- Knowledge Link v0.4 (docs/features/Knowledge_Link_기능정의서_v0.4.md)
-- 노드 식별자는 저장소가 아니라 애플리케이션이 채번한다.

CREATE TABLE knowledge_node (
  id uuid PRIMARY KEY,
  user_id bigint NOT NULL,
  node_type varchar(20) NOT NULL,
  title varchar(500) NOT NULL,
  normalized_title varchar(500) NOT NULL,
  description text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE knowledge_source (
  node_id uuid PRIMARY KEY,
  folder_id bigint NOT NULL,
  url text NOT NULL,
  canonical_url text NOT NULL,
  content text,
  summary text,
  source_type varchar(50),
  author varchar(255),
  published_at timestamptz,
  processing_status varchar(20) NOT NULL DEFAULT 'PENDING',
  analysis_version integer,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 사용자가 만든 소속 / 구조. 의미는 담지 않는다.
CREATE TABLE knowledge_branch (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_node_id uuid NOT NULL,
  child_node_id uuid NOT NULL,
  position integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Swimming이 해석한 지식의 의미 연결.
CREATE TABLE knowledge_relation (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_node_id uuid NOT NULL,
  to_node_id uuid NOT NULL,
  relation_type varchar(20) NOT NULL,
  origin varchar(20) NOT NULL,
  confidence double precision,
  evidence jsonb,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_knowledge_node_user_type ON knowledge_node (user_id, node_type);

-- 같은 개념이 표기만 달라 여러 Subject로 갈라지는 것을 막는다.
-- SUBJECT만 대상이다. SOURCE는 제목이 같은 다른 문서를 저장할 수 있어야 하고,
-- TOPIC은 Source마다 새로 만들어 재사용 판정을 하지 않는다.
CREATE UNIQUE INDEX uq_knowledge_node_normalized
  ON knowledge_node (user_id, node_type, normalized_title)
  WHERE node_type = 'SUBJECT';

CREATE INDEX idx_knowledge_source_canonical_url ON knowledge_source (canonical_url);

CREATE INDEX idx_knowledge_source_folder ON knowledge_source (folder_id);

CREATE INDEX idx_knowledge_branch_parent ON knowledge_branch (parent_node_id);

CREATE INDEX idx_knowledge_branch_child ON knowledge_branch (child_node_id);

CREATE UNIQUE INDEX uq_knowledge_branch
  ON knowledge_branch (parent_node_id, child_node_id);

CREATE INDEX idx_knowledge_relation_from_type
  ON knowledge_relation (from_node_id, relation_type);

CREATE INDEX idx_knowledge_relation_to_type
  ON knowledge_relation (to_node_id, relation_type);

CREATE UNIQUE INDEX uq_knowledge_relation
  ON knowledge_relation (from_node_id, to_node_id, relation_type);

ALTER TABLE knowledge_node
  ADD CONSTRAINT fk_knowledge_node_user
  FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE knowledge_source
  ADD CONSTRAINT fk_knowledge_source_node
  FOREIGN KEY (node_id) REFERENCES knowledge_node (id) ON DELETE CASCADE;

ALTER TABLE knowledge_source
  ADD CONSTRAINT fk_knowledge_source_folder
  FOREIGN KEY (folder_id) REFERENCES folders (id);

ALTER TABLE knowledge_branch
  ADD CONSTRAINT fk_knowledge_branch_parent
  FOREIGN KEY (parent_node_id) REFERENCES knowledge_node (id) ON DELETE CASCADE;

ALTER TABLE knowledge_branch
  ADD CONSTRAINT fk_knowledge_branch_child
  FOREIGN KEY (child_node_id) REFERENCES knowledge_node (id) ON DELETE CASCADE;

ALTER TABLE knowledge_relation
  ADD CONSTRAINT fk_knowledge_relation_from
  FOREIGN KEY (from_node_id) REFERENCES knowledge_node (id) ON DELETE CASCADE;

ALTER TABLE knowledge_relation
  ADD CONSTRAINT fk_knowledge_relation_to
  FOREIGN KEY (to_node_id) REFERENCES knowledge_node (id) ON DELETE CASCADE;
