CREATE TABLE task_organizer_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  note_id bigint NOT NULL,
  status varchar(20) NOT NULL,
  input_snapshot jsonb NOT NULL,
  preview_snapshot jsonb NOT NULL,
  feedback_snapshot jsonb,
  llm_calls jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_task_organizer_runs_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_task_organizer_runs_note FOREIGN KEY (note_id) REFERENCES notes (id)
);

CREATE INDEX idx_task_organizer_runs_user_created
  ON task_organizer_runs (user_id, created_at DESC);

CREATE INDEX idx_task_organizer_runs_note_created
  ON task_organizer_runs (note_id, created_at DESC);
