spring:
  application:
    name: backend
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: UTC
  mvc:
    problemdetails:
      enabled: true

app:
  place:
    background:
      cdn-base-url: ${PLACE_CDN_BASE_URL}
