spring:
  config:
    import:
      - classpath:llm/openai.yml
      - classpath:llm/openai-embedding.yml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    baseline-on-migrate: false
    clean-disabled: true

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 1h
  refresh-token-validity: 14d

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
  auth:
    secure-cookie: true
    google:
      client-id: ${GOOGLE_CLIENT_ID}

logging:
  level:
    root: INFO
